#!/usr/bin/env python3
"""Convert monospace BDF fonts (Spleen) into a C++ header of fixed-cell bitmaps.

Each glyph is packed into a WxH cell, row-major, MSB = leftmost pixel,
bytesPerRow = ceil(W/8). Covers printable ASCII 0x20..0x7E.
"""
import sys, os

def parse_bdf(path):
    with open(path) as f:
        lines = f.read().splitlines()
    i = 0
    fbbx = fbby = fbxoff = fbyoff = 0
    glyphs = {}
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("FONTBOUNDINGBOX"):
            _, fbbx, fbby, fbxoff, fbyoff = ln.split()
            fbbx, fbby, fbxoff, fbyoff = int(fbbx), int(fbby), int(fbxoff), int(fbyoff)
        elif ln.startswith("STARTCHAR"):
            enc = None; bbx = None; bitmap = []
            while not lines[i].startswith("ENDCHAR"):
                i += 1
                if lines[i].startswith("ENCODING"):
                    enc = int(lines[i].split()[1])
                elif lines[i].startswith("BBX"):
                    _, bw, bh, bxo, byo = lines[i].split()
                    bbx = (int(bw), int(bh), int(bxo), int(byo))
                elif lines[i] == "BITMAP":
                    j = i + 1
                    while not lines[j].startswith("ENDCHAR"):
                        bitmap.append(lines[j].strip()); j += 1
                    i = j - 1
            if enc is not None and bbx is not None:
                glyphs[enc] = (bbx, bitmap)
        i += 1
    return (fbbx, fbby, fbxoff, fbyoff), glyphs

def cell_for(glyph, fbb):
    fbbx, fbby, fbxoff, fbyoff = fbb
    (bw, bh, bxo, byo), bitmap = glyph
    cell = [[0] * fbbx for _ in range(fbby)]
    baseline = fbby + fbyoff
    top = baseline - bh - byo
    left = bxo - fbxoff
    hexdigits = (bw + 7) // 8 * 2
    for r, row in enumerate(bitmap):
        row = row.zfill(hexdigits)
        val = int(row, 16) if row else 0
        for c in range(bw):
            bit = (val >> (hexdigits * 4 - 1 - c)) & 1
            if bit:
                y = top + r; x = left + c
                if 0 <= y < fbby and 0 <= x < fbbx:
                    cell[y][x] = 1
    return cell

def pack(cell, w):
    bpr = (w + 7) // 8
    out = []
    for row in cell:
        for b in range(bpr):
            byte = 0
            for bit in range(8):
                x = b * 8 + bit
                if x < w and row[x]:
                    byte |= 1 << (7 - bit)
            out.append(byte)
    return out, bpr

def emit(name, path, out):
    fbb, glyphs = parse_bdf(path)
    w, h = fbb[0], fbb[1]
    bpr = (w + 7) // 8
    out.write(f"// {name}: {w}x{h}, {bpr} byte(s)/row, ASCII 0x20-0x7E\n")
    out.write(f"inline constexpr uint8_t kData_{name}[95][{h * bpr}] = {{\n")
    for code in range(0x20, 0x7F):
        g = glyphs.get(code)
        if g is None:
            data = [0] * (h * bpr)
        else:
            cell = cell_for(g, fbb)
            data, _ = pack(cell, w)
        hexed = ", ".join(f"0x{b:02X}" for b in data)
        out.write(f"    {{{hexed}}},  // 0x{code:02X} {chr(code)!r}\n")
    out.write("};\n")
    out.write(f"inline constexpr BitmapFont k{name}{{{w}, {h}, {bpr}, &kData_{name}[0][0]}};\n\n")
    return w, h

if __name__ == "__main__":
    fonts = [
        ("Spleen6x12", "third_party/fonts/spleen-6x12.bdf"),
        ("Spleen8x16", "third_party/fonts/spleen-8x16.bdf"),
        ("Spleen12x24", "third_party/fonts/spleen-12x24.bdf"),
    ]
    dst = "include/mc/adapters/mcu/SpleenFont.h"
    with open(dst, "w") as out:
        out.write("#pragma once\n")
        out.write("// GENERATED by tools/bdf_to_header.py from Spleen (BSD-2-Clause,\n")
        out.write("// (c) Frederic Cambus). Do not edit by hand.\n#include <cstdint>\n\n")
        out.write("namespace mc::mcu {\n\n")
        out.write("struct BitmapFont {\n")
        out.write("    int w, h, bytesPerRow;\n")
        out.write("    const uint8_t* data;  // [95][h*bytesPerRow], glyph 0 = 0x20\n")
        out.write("    const uint8_t* glyph(char c) const {\n")
        out.write("        unsigned u = static_cast<unsigned char>(c);\n")
        out.write("        if (u < 0x20 || u > 0x7E) u = 0x20;\n")
        out.write("        return data + (u - 0x20) * h * bytesPerRow;\n")
        out.write("    }\n};\n\n")
        for name, path in fonts:
            emit(name, path, out)
        out.write("}  // namespace mc::mcu\n")
    print(f"wrote {dst}")
