#!/usr/bin/env python3
"""Bake data/*.json into a C++ source file for the MCU build (flash-resident config).

Emits EmbeddedData.cpp defining mc::mcu::kEmbeddedData[] / kEmbeddedDataCount,
keyed by path relative to the data dir (e.g. "pedals/TimeLine.json"). Run by the
Pico CMake build automatically.

Usage: python3 tools/embed_data.py <DATA_DIR> <OUT_CPP>
"""
import os
import sys


def main():
    src = sys.argv[1]
    out = sys.argv[2]

    entries = []
    for root, _, files in os.walk(src):
        for name in sorted(files):
            if not name.endswith(".json"):
                continue
            full = os.path.join(root, name)
            key = os.path.relpath(full, src).replace(os.sep, "/")
            with open(full, "rb") as fh:
                entries.append((key, fh.read()))
    entries.sort(key=lambda e: e[0])

    lines = [
        "// GENERATED by tools/embed_data.py — do not edit.",
        '#include "mc/adapters/mcu/EmbeddedData.h"',
        "namespace mc::mcu {",
    ]
    for i, (_, data) in enumerate(entries):
        body = ",".join(str(b) for b in data)
        lines.append("static const unsigned char kBlob{}[] = {{{}}};".format(i, body))
    lines.append("const EmbeddedBlob kEmbeddedData[] = {")
    for i, (key, data) in enumerate(entries):
        esc = key.replace("\\", "\\\\").replace('"', '\\"')
        lines.append('  {{"{}", reinterpret_cast<const char*>(kBlob{}), {}}},'.format(esc, i, len(data)))
    lines.append("};")
    lines.append("const size_t kEmbeddedDataCount = {};".format(len(entries)))
    lines.append("}  // namespace mc::mcu")

    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("embedded {} blobs -> {}".format(len(entries), out))


if __name__ == "__main__":
    main()
