#!/usr/bin/env python3
"""Generate include/mc/adapters/mcu/Ssd1306Font.h from the Adafruit GFX glcdfont
(public domain). One-shot dev tool: run it, eyeball the verification render, commit
the header. The font is column-major, bit0 = top pixel — exactly what the SSD1306
driver expects, so glyph bytes go straight into the page framebuffer.

Usage: python3 tools/gen_font.py            (fetches the font)
       python3 tools/gen_font.py glcdfont.c (uses a local copy)
"""
import os
import re
import sys

URL = "https://raw.githubusercontent.com/adafruit/Adafruit-GFX-Library/master/glcdfont.c"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "include", "mc", "adapters", "mcu", "Ssd1306Font.h")
LO, HI = 0x20, 0x7E  # printable ASCII


def load_bytes():
    if len(sys.argv) > 1:
        txt = open(sys.argv[1], "r", encoding="latin-1").read()
    else:
        import urllib.request
        txt = urllib.request.urlopen(URL, timeout=30).read().decode("latin-1")
    return [int(x, 16) for x in re.findall(r"0[xX]([0-9a-fA-F]{2})", txt)]


def render(nums, c):
    cols = nums[c * 5: c * 5 + 5]
    print("--- {!r} (0x{:02X})".format(chr(c), c))
    for row in range(8):
        print("  " + "".join("#" if (cols[col] >> row) & 1 else "." for col in range(5)))


def main():
    nums = load_bytes()
    if len(nums) < (HI + 1) * 5:
        raise SystemExit("font data too short: {} bytes".format(len(nums)))

    for c in [0x20, 0x21, 0x30, 0x39, 0x41, 0x5A, 0x61, 0x7A, 0x3A, 0x2D]:
        render(nums, c)

    lines = [
        "#pragma once",
        "// GENERATED by tools/gen_font.py from the Adafruit GFX glcdfont (public domain).",
        "// 5 columns per glyph, bit0 = top pixel. Covers printable ASCII 0x20..0x7E.",
        "#include <cstdint>",
        "",
        "namespace mc::mcu {",
        "",
        "inline const uint8_t* glyph5x7(char c) {",
        "    static const uint8_t kFont[{}][5] = {{".format(HI - LO + 1),
    ]
    for c in range(LO, HI + 1):
        cols = nums[c * 5: c * 5 + 5]
        body = ", ".join("0x{:02X}".format(b) for b in cols)
        disp = chr(c) if c != 0x5C else "(backslash)"
        lines.append("        {{{}}},  // 0x{:02X} {}".format(body, c, disp))
    lines += [
        "    };",
        "    static const uint8_t kBox[5] = {0x7F, 0x41, 0x41, 0x41, 0x7F};",
        "    unsigned u = static_cast<unsigned char>(c);",
        "    if (u < 0x20u || u > 0x7Eu) return kBox;",
        "    return kFont[u - 0x20u];",
        "}",
        "",
        "}  // namespace mc::mcu",
        "",
    ]
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print("\nwrote {} glyphs -> {}".format(HI - LO + 1, OUT))


if __name__ == "__main__":
    main()
